Fix neutron template for dhcp_agents_per_network
A value of False raises the exception:
NoSuchOptError: no such option: dhcp_agents_per_network

If the option is not required this patch will keep it out of the conf
file.

Issue: #973